-- GENERATED — applied after additive columns exist.

CREATE UNIQUE INDEX IF NOT EXISTS idx_person_email ON person (lower(email));
CREATE INDEX IF NOT EXISTS idx_membership_person ON membership (person_id);
CREATE INDEX IF NOT EXISTS idx_session_person ON session (person_id);
CREATE INDEX IF NOT EXISTS idx_event_org_at ON event_log (org_id, at DESC);
CREATE INDEX IF NOT EXISTS idx_event_type ON event_log (org_id, type, at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_org_at ON audit_log (org_id, at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_subject ON audit_log (org_id, subject, at DESC);
CREATE INDEX IF NOT EXISTS idx_founding_status ON founding_milestone (org_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_season ON fin_budget (org_id, season);
CREATE INDEX IF NOT EXISTS idx_cost_budget ON fin_cost (org_id, budget_id);
CREATE INDEX IF NOT EXISTS idx_income_budget ON fin_income (org_id, budget_id);
CREATE INDEX IF NOT EXISTS idx_field_org ON land_field (org_id);
CREATE INDEX IF NOT EXISTS idx_bed_org_field ON land_bed (org_id, field_id);
CREATE INDEX IF NOT EXISTS idx_feature_org ON land_feature (org_id, kind);
CREATE INDEX IF NOT EXISTS idx_perennial_org ON land_perennial (org_id);
CREATE INDEX IF NOT EXISTS idx_soil_field ON land_soil_sample (org_id, field_id, taken_on DESC);
CREATE INDEX IF NOT EXISTS idx_feature_org_kind ON land_feature (org_id, kind);
CREATE INDEX IF NOT EXISTS idx_crop_org ON cult_crop (org_id);
CREATE INDEX IF NOT EXISTS idx_crop_family ON cult_crop (org_id, family);
CREATE INDEX IF NOT EXISTS idx_planting_org_bed ON cult_planting (org_id, bed_id);
CREATE INDEX IF NOT EXISTS idx_planting_dates ON cult_planting (org_id, harvest_from, harvest_to);
CREATE INDEX IF NOT EXISTS idx_task_org_status ON task (org_id, status, window_to);
CREATE INDEX IF NOT EXISTS idx_task_bed ON task (org_id, bed_id);
CREATE INDEX IF NOT EXISTS idx_task_board ON task (org_id, board_column, board_order);
CREATE INDEX IF NOT EXISTS idx_depot_org ON depot (org_id, active);
CREATE INDEX IF NOT EXISTS idx_distday ON distribution_day (org_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_distitem ON distribution_item (org_id, day_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_pickup_unique ON pickup (org_id, day_id, household_id);
CREATE INDEX IF NOT EXISTS idx_household_org ON household (org_id);
CREATE INDEX IF NOT EXISTS idx_sharetype_org ON share_type (org_id);
CREATE INDEX IF NOT EXISTS idx_share_org_season ON share (org_id, season);
CREATE INDEX IF NOT EXISTS idx_absence_dates ON absence (org_id, from_date, to_date);
CREATE INDEX IF NOT EXISTS idx_connect_to ON connect_request (org_id, to_household, status);
CREATE INDEX IF NOT EXISTS idx_round_org ON bid_round (org_id, season, ordinal);
CREATE INDEX IF NOT EXISTS idx_bid_round ON bid (org_id, round_id, household_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inv_org ON inv_item (org_id, kind);
CREATE INDEX IF NOT EXISTS idx_loan_open ON inv_loan (org_id, item_id, returned_at);
CREATE INDEX IF NOT EXISTS idx_obs_bed_time ON observation (org_id, bed_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_obs_activity ON observation (org_id, activity, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_status ON feedback_report (status, created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_org ON feedback_report (org_id, created_at DESC);
